### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by JasonKeirstead** [Soltra/cti-stats#4]
After I fixed issue #2 and issue #3 I now got this issue:

```
Traceback (most recent call last):
  File "./cti-stats", line 69, in <module>
    main()
  File "./cti-stats", line 63, in main
    args['--use-ssl'], args['--validate-cert'])
TypeError: 'NoneType' object is not iterable
```

My python-fu dried up at this point, not sure what is going on. I verified that I am receiving a ton of STIX back from my server.

**Comment by treyka** [comment]
@JasonKeirstead Thanks for the issue, I'll get on this pronto! ^_^

**Comment by treyka** [comment]
Appears to be fixed, closing the issue.
